### ISSUE TITLE
Food not received

### ISSUE THREAD

**Issue by pradeepgangwar** [sashank27/Caviar#1]
@sashank27 I got a call from our TA who evaluated this project yesterday. He complained that he has not received his food order yet. So I request you to kindly look into this and fix this problem. Else we need to close this project.

**Comment by shreyanshdwivedi** [comment]
@pradeepgangwar I remember that you were appointed as delivery boy for this project. Please leave all other works and complete this important task, otherwise you will be removed from our project xD

**Comment by Anupam-dagar** [comment]
seen
sent from my samsung galaxy note 8

**Comment by sashank27** [comment]
I had a talk with the TA, and I discovered that the delivery boy @pradeepgangwar was into some personal work, and so couldn't attend to the delivery.
This issue is resolved as of now, and @pradeepgangwar is warned not to show such carelessness in the future :smiley:
